services:
  postgres:
    image: postgres:15.3
    container_name: ci-postgres
    environment:
      POSTGRES_DB: taskvault_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d taskvault_db"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    image: ghcr.io/${OWNER_LC}/taskvault-api:${IMAGE_TAG}
    container_name: ci-api
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      RUN_MODE: PRODUCTION
      DATABASE_URL: jdbc:postgresql://postgres:5432/taskvault_db
      DATABASE_USER: admin
      DATABASE_PASSWORD: admin
    ports:
      - "8080:8080"